#!/bin/bash
#
# Decode FLAC to raw 16-bit little-endian PCM.
# Compute the MD5 sum over raw PCM.
# Compare it with the checksum stored in the FLAC header.
#
# Use flac -t *.flac instead of this script whenever possible.

set -o pipefail
RETVAL=0

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 FILE [FILE...]" >&2
  exit 1
fi

for TRACK in "$@"; do
  if [[ ! -f "$TRACK" ]]; then
    echo "Skipping non-regular path: $TRACK" >&2
    continue
  fi

  MIME=$(file --mime-type -b -- "$TRACK")
  if [[ "$MIME" = "audio/flac" ]]; then
    metadata_md5=$(metaflac --show-md5sum -- "$TRACK")
    actual_md5=$(flac --decode --stdout --totally-silent --force-raw-format --endian=little --sign=signed -- "$TRACK" | md5sum | cut -f 1 -d ' ')

    if [[ "$metadata_md5" == "$actual_md5" ]]; then
        STATUS="OK"
    else
        STATUS="FAILED"
        RETVAL=1
    fi

    printf "%s\t%s\t%s\n" "$actual_md5" "$TRACK" "$STATUS"
  else
    echo "Not FLAC (mime=$MIME): $TRACK" >&2
  fi
done

exit $RETVAL
